import Colegio from "./ConstrutoraCursos"
/* 
id, 
nomeDoCurso, 
cidade, 
modalidade, 
especializacao, 
parceiro, 
precoCheio, 
porcentagemDesconto, 
campus, 
sobre, 
duracao, 
urlImage
*/
export const colegios = [
    new Colegio(
        1, 
        "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),
    new Colegio(
        1, "Ensino Infantil - G3 ao G5", 
        "Salvador", 
        "Modalidade", 
        "Especialização",
        "Parceiro",
        500,
        45,
        "Salvador",
        "Curso Muito Bom!!",
        "1 ano",
        ),

]